# Generated by Django 4.2.16 on 2026-06-13 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "reorder_point",
                    models.IntegerField(
                        default=10,
                        help_text="Stock level that triggers a reorder alert",
                    ),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(
                        default=50, help_text="Recommended quantity to reorder"
                    ),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("supplier_email", models.EmailField(blank=True, max_length=254)),
                (
                    "lead_time_days",
                    models.IntegerField(
                        default=7, help_text="Days from order to delivery"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="forecasting.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("overstock", "Overstock"),
                            ("demand_spike", "Demand Spike"),
                            ("reorder_needed", "Reorder Needed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "🔴 Critical"),
                            ("warning", "🟡 Warning"),
                            ("info", "🔵 Info"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "forecast_demand",
                    models.FloatField(
                        blank=True,
                        help_text="Forecasted demand that triggered this alert",
                        null=True,
                    ),
                ),
                ("days_until_stockout", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="forecasting.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_level", models.IntegerField()),
                (
                    "change_amount",
                    models.IntegerField(
                        help_text="Positive = stock in, Negative = stock out"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("restock", "Restock"),
                            ("adjustment", "Adjustment"),
                            ("api_sync", "API Sync"),
                        ],
                        default="api_sync",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="simulated_api", max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_logs",
                        to="forecasting.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New Session", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")], max_length=10
                    ),
                ),
                ("text", models.TextField()),
                (
                    "chart_config",
                    models.JSONField(
                        blank=True,
                        help_text="Chart.js config for inline chart rendering",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="forecasting.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_store", "In-Store"),
                            ("wholesale", "Wholesale"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_records",
                        to="forecasting.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "product"], name="forecasting_date_5e8779_idx"
                    ),
                    models.Index(
                        fields=["product", "date"],
                        name="forecasting_product_2fda46_idx",
                    ),
                ],
                "unique_together": {("product", "date", "channel")},
            },
        ),
        migrations.CreateModel(
            name="ForecastCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[("prophet", "Prophet"), ("rf", "RandomForest")],
                        default="prophet",
                        max_length=20,
                    ),
                ),
                ("horizon_days", models.IntegerField(default=30)),
                (
                    "forecast_data",
                    models.JSONField(
                        help_text="Serialized forecast: [{date, yhat, yhat_lower, yhat_upper}]"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_cache",
                        to="forecasting.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "unique_together": {("product", "model_type", "horizon_days")},
            },
        ),
    ]
